// Swedish municipalities (kommunkod -> name, county), from SCB's Region variable
// (api.scb.se BE0101A/BefolkningNy), fetched 2026-10-02. 290 kommuner.
export const KOMMUNER: Record<string, { name: string; county: string }> = {
    "0114": { name: "Upplands Väsby", county: "Stockholms län" },
    "0115": { name: "Vallentuna", county: "Stockholms län" },
    "0117": { name: "Österåker", county: "Stockholms län" },
    "0120": { name: "Värmdö", county: "Stockholms län" },
    "0123": { name: "Järfälla", county: "Stockholms län" },
    "0125": { name: "Ekerö", county: "Stockholms län" },
    "0126": { name: "Huddinge", county: "Stockholms län" },
    "0127": { name: "Botkyrka", county: "Stockholms län" },
    "0128": { name: "Salem", county: "Stockholms län" },
    "0136": { name: "Haninge", county: "Stockholms län" },
    "0138": { name: "Tyresö", county: "Stockholms län" },
    "0139": { name: "Upplands-Bro", county: "Stockholms län" },
    "0140": { name: "Nykvarn", county: "Stockholms län" },
    "0160": { name: "Täby", county: "Stockholms län" },
    "0162": { name: "Danderyd", county: "Stockholms län" },
    "0163": { name: "Sollentuna", county: "Stockholms län" },
    "0180": { name: "Stockholm", county: "Stockholms län" },
    "0181": { name: "Södertälje", county: "Stockholms län" },
    "0182": { name: "Nacka", county: "Stockholms län" },
    "0183": { name: "Sundbyberg", county: "Stockholms län" },
    "0184": { name: "Solna", county: "Stockholms län" },
    "0186": { name: "Lidingö", county: "Stockholms län" },
    "0187": { name: "Vaxholm", county: "Stockholms län" },
    "0188": { name: "Norrtälje", county: "Stockholms län" },
    "0191": { name: "Sigtuna", county: "Stockholms län" },
    "0192": { name: "Nynäshamn", county: "Stockholms län" },
    "0305": { name: "Håbo", county: "Uppsala län" },
    "0319": { name: "Älvkarleby", county: "Uppsala län" },
    "0330": { name: "Knivsta", county: "Uppsala län" },
    "0331": { name: "Heby", county: "Uppsala län" },
    "0360": { name: "Tierp", county: "Uppsala län" },
    "0380": { name: "Uppsala", county: "Uppsala län" },
    "0381": { name: "Enköping", county: "Uppsala län" },
    "0382": { name: "Östhammar", county: "Uppsala län" },
    "0428": { name: "Vingåker", county: "Södermanlands län" },
    "0461": { name: "Gnesta", county: "Södermanlands län" },
    "0480": { name: "Nyköping", county: "Södermanlands län" },
    "0481": { name: "Oxelösund", county: "Södermanlands län" },
    "0482": { name: "Flen", county: "Södermanlands län" },
    "0483": { name: "Katrineholm", county: "Södermanlands län" },
    "0484": { name: "Eskilstuna", county: "Södermanlands län" },
    "0486": { name: "Strängnäs", county: "Södermanlands län" },
    "0488": { name: "Trosa", county: "Södermanlands län" },
    "0509": { name: "Ödeshög", county: "Östergötlands län" },
    "0512": { name: "Ydre", county: "Östergötlands län" },
    "0513": { name: "Kinda", county: "Östergötlands län" },
    "0560": { name: "Boxholm", county: "Östergötlands län" },
    "0561": { name: "Åtvidaberg", county: "Östergötlands län" },
    "0562": { name: "Finspång", county: "Östergötlands län" },
    "0563": { name: "Valdemarsvik", county: "Östergötlands län" },
    "0580": { name: "Linköping", county: "Östergötlands län" },
    "0581": { name: "Norrköping", county: "Östergötlands län" },
    "0582": { name: "Söderköping", county: "Östergötlands län" },
    "0583": { name: "Motala", county: "Östergötlands län" },
    "0584": { name: "Vadstena", county: "Östergötlands län" },
    "0586": { name: "Mjölby", county: "Östergötlands län" },
    "0604": { name: "Aneby", county: "Jönköpings län" },
    "0617": { name: "Gnosjö", county: "Jönköpings län" },
    "0642": { name: "Mullsjö", county: "Jönköpings län" },
    "0643": { name: "Habo", county: "Jönköpings län" },
    "0662": { name: "Gislaved", county: "Jönköpings län" },
    "0665": { name: "Vaggeryd", county: "Jönköpings län" },
    "0680": { name: "Jönköping", county: "Jönköpings län" },
    "0682": { name: "Nässjö", county: "Jönköpings län" },
    "0683": { name: "Värnamo", county: "Jönköpings län" },
    "0684": { name: "Sävsjö", county: "Jönköpings län" },
    "0685": { name: "Vetlanda", county: "Jönköpings län" },
    "0686": { name: "Eksjö", county: "Jönköpings län" },
    "0687": { name: "Tranås", county: "Jönköpings län" },
    "0760": { name: "Uppvidinge", county: "Kronobergs län" },
    "0761": { name: "Lessebo", county: "Kronobergs län" },
    "0763": { name: "Tingsryd", county: "Kronobergs län" },
    "0764": { name: "Alvesta", county: "Kronobergs län" },
    "0765": { name: "Älmhult", county: "Kronobergs län" },
    "0767": { name: "Markaryd", county: "Kronobergs län" },
    "0780": { name: "Växjö", county: "Kronobergs län" },
    "0781": { name: "Ljungby", county: "Kronobergs län" },
    "0821": { name: "Högsby", county: "Kalmar län" },
    "0834": { name: "Torsås", county: "Kalmar län" },
    "0840": { name: "Mörbylånga", county: "Kalmar län" },
    "0860": { name: "Hultsfred", county: "Kalmar län" },
    "0861": { name: "Mönsterås", county: "Kalmar län" },
    "0862": { name: "Emmaboda", county: "Kalmar län" },
    "0880": { name: "Kalmar", county: "Kalmar län" },
    "0881": { name: "Nybro", county: "Kalmar län" },
    "0882": { name: "Oskarshamn", county: "Kalmar län" },
    "0883": { name: "Västervik", county: "Kalmar län" },
    "0884": { name: "Vimmerby", county: "Kalmar län" },
    "0885": { name: "Borgholm", county: "Kalmar län" },
    "0980": { name: "Gotland", county: "Gotlands län" },
    "1060": { name: "Olofström", county: "Blekinge län" },
    "1080": { name: "Karlskrona", county: "Blekinge län" },
    "1081": { name: "Ronneby", county: "Blekinge län" },
    "1082": { name: "Karlshamn", county: "Blekinge län" },
    "1083": { name: "Sölvesborg", county: "Blekinge län" },
    "1214": { name: "Svalöv", county: "Skåne län" },
    "1230": { name: "Staffanstorp", county: "Skåne län" },
    "1231": { name: "Burlöv", county: "Skåne län" },
    "1233": { name: "Vellinge", county: "Skåne län" },
    "1256": { name: "Östra Göinge", county: "Skåne län" },
    "1257": { name: "Örkelljunga", county: "Skåne län" },
    "1260": { name: "Bjuv", county: "Skåne län" },
    "1261": { name: "Kävlinge", county: "Skåne län" },
    "1262": { name: "Lomma", county: "Skåne län" },
    "1263": { name: "Svedala", county: "Skåne län" },
    "1264": { name: "Skurup", county: "Skåne län" },
    "1265": { name: "Sjöbo", county: "Skåne län" },
    "1266": { name: "Hörby", county: "Skåne län" },
    "1267": { name: "Höör", county: "Skåne län" },
    "1270": { name: "Tomelilla", county: "Skåne län" },
    "1272": { name: "Bromölla", county: "Skåne län" },
    "1273": { name: "Osby", county: "Skåne län" },
    "1275": { name: "Perstorp", county: "Skåne län" },
    "1276": { name: "Klippan", county: "Skåne län" },
    "1277": { name: "Åstorp", county: "Skåne län" },
    "1278": { name: "Båstad", county: "Skåne län" },
    "1280": { name: "Malmö", county: "Skåne län" },
    "1281": { name: "Lund", county: "Skåne län" },
    "1282": { name: "Landskrona", county: "Skåne län" },
    "1283": { name: "Helsingborg", county: "Skåne län" },
    "1284": { name: "Höganäs", county: "Skåne län" },
    "1285": { name: "Eslöv", county: "Skåne län" },
    "1286": { name: "Ystad", county: "Skåne län" },
    "1287": { name: "Trelleborg", county: "Skåne län" },
    "1290": { name: "Kristianstad", county: "Skåne län" },
    "1291": { name: "Simrishamn", county: "Skåne län" },
    "1292": { name: "Ängelholm", county: "Skåne län" },
    "1293": { name: "Hässleholm", county: "Skåne län" },
    "1315": { name: "Hylte", county: "Hallands län" },
    "1380": { name: "Halmstad", county: "Hallands län" },
    "1381": { name: "Laholm", county: "Hallands län" },
    "1382": { name: "Falkenberg", county: "Hallands län" },
    "1383": { name: "Varberg", county: "Hallands län" },
    "1384": { name: "Kungsbacka", county: "Hallands län" },
    "1401": { name: "Härryda", county: "Västra Götalands län" },
    "1402": { name: "Partille", county: "Västra Götalands län" },
    "1407": { name: "Öckerö", county: "Västra Götalands län" },
    "1415": { name: "Stenungsund", county: "Västra Götalands län" },
    "1419": { name: "Tjörn", county: "Västra Götalands län" },
    "1421": { name: "Orust", county: "Västra Götalands län" },
    "1427": { name: "Sotenäs", county: "Västra Götalands län" },
    "1430": { name: "Munkedal", county: "Västra Götalands län" },
    "1435": { name: "Tanum", county: "Västra Götalands län" },
    "1438": { name: "Dals-Ed", county: "Västra Götalands län" },
    "1439": { name: "Färgelanda", county: "Västra Götalands län" },
    "1440": { name: "Ale", county: "Västra Götalands län" },
    "1441": { name: "Lerum", county: "Västra Götalands län" },
    "1442": { name: "Vårgårda", county: "Västra Götalands län" },
    "1443": { name: "Bollebygd", county: "Västra Götalands län" },
    "1444": { name: "Grästorp", county: "Västra Götalands län" },
    "1445": { name: "Essunga", county: "Västra Götalands län" },
    "1446": { name: "Karlsborg", county: "Västra Götalands län" },
    "1447": { name: "Gullspång", county: "Västra Götalands län" },
    "1452": { name: "Tranemo", county: "Västra Götalands län" },
    "1460": { name: "Bengtsfors", county: "Västra Götalands län" },
    "1461": { name: "Mellerud", county: "Västra Götalands län" },
    "1462": { name: "Lilla Edet", county: "Västra Götalands län" },
    "1463": { name: "Mark", county: "Västra Götalands län" },
    "1465": { name: "Svenljunga", county: "Västra Götalands län" },
    "1466": { name: "Herrljunga", county: "Västra Götalands län" },
    "1470": { name: "Vara", county: "Västra Götalands län" },
    "1471": { name: "Götene", county: "Västra Götalands län" },
    "1472": { name: "Tibro", county: "Västra Götalands län" },
    "1473": { name: "Töreboda", county: "Västra Götalands län" },
    "1480": { name: "Göteborg", county: "Västra Götalands län" },
    "1481": { name: "Mölndal", county: "Västra Götalands län" },
    "1482": { name: "Kungälv", county: "Västra Götalands län" },
    "1484": { name: "Lysekil", county: "Västra Götalands län" },
    "1485": { name: "Uddevalla", county: "Västra Götalands län" },
    "1486": { name: "Strömstad", county: "Västra Götalands län" },
    "1487": { name: "Vänersborg", county: "Västra Götalands län" },
    "1488": { name: "Trollhättan", county: "Västra Götalands län" },
    "1489": { name: "Alingsås", county: "Västra Götalands län" },
    "1490": { name: "Borås", county: "Västra Götalands län" },
    "1491": { name: "Ulricehamn", county: "Västra Götalands län" },
    "1492": { name: "Åmål", county: "Västra Götalands län" },
    "1493": { name: "Mariestad", county: "Västra Götalands län" },
    "1494": { name: "Lidköping", county: "Västra Götalands län" },
    "1495": { name: "Skara", county: "Västra Götalands län" },
    "1496": { name: "Skövde", county: "Västra Götalands län" },
    "1497": { name: "Hjo", county: "Västra Götalands län" },
    "1498": { name: "Tidaholm", county: "Västra Götalands län" },
    "1499": { name: "Falköping", county: "Västra Götalands län" },
    "1715": { name: "Kil", county: "Värmlands län" },
    "1730": { name: "Eda", county: "Värmlands län" },
    "1737": { name: "Torsby", county: "Värmlands län" },
    "1760": { name: "Storfors", county: "Värmlands län" },
    "1761": { name: "Hammarö", county: "Värmlands län" },
    "1762": { name: "Munkfors", county: "Värmlands län" },
    "1763": { name: "Forshaga", county: "Värmlands län" },
    "1764": { name: "Grums", county: "Värmlands län" },
    "1765": { name: "Årjäng", county: "Värmlands län" },
    "1766": { name: "Sunne", county: "Värmlands län" },
    "1780": { name: "Karlstad", county: "Värmlands län" },
    "1781": { name: "Kristinehamn", county: "Värmlands län" },
    "1782": { name: "Filipstad", county: "Värmlands län" },
    "1783": { name: "Hagfors", county: "Värmlands län" },
    "1784": { name: "Arvika", county: "Värmlands län" },
    "1785": { name: "Säffle", county: "Värmlands län" },
    "1814": { name: "Lekeberg", county: "Örebro län" },
    "1860": { name: "Laxå", county: "Örebro län" },
    "1861": { name: "Hallsberg", county: "Örebro län" },
    "1862": { name: "Degerfors", county: "Örebro län" },
    "1863": { name: "Hällefors", county: "Örebro län" },
    "1864": { name: "Ljusnarsberg", county: "Örebro län" },
    "1880": { name: "Örebro", county: "Örebro län" },
    "1881": { name: "Kumla", county: "Örebro län" },
    "1882": { name: "Askersund", county: "Örebro län" },
    "1883": { name: "Karlskoga", county: "Örebro län" },
    "1884": { name: "Nora", county: "Örebro län" },
    "1885": { name: "Lindesberg", county: "Örebro län" },
    "1904": { name: "Skinnskatteberg", county: "Västmanlands län" },
    "1907": { name: "Surahammar", county: "Västmanlands län" },
    "1960": { name: "Kungsör", county: "Västmanlands län" },
    "1961": { name: "Hallstahammar", county: "Västmanlands län" },
    "1962": { name: "Norberg", county: "Västmanlands län" },
    "1980": { name: "Västerås", county: "Västmanlands län" },
    "1981": { name: "Sala", county: "Västmanlands län" },
    "1982": { name: "Fagersta", county: "Västmanlands län" },
    "1983": { name: "Köping", county: "Västmanlands län" },
    "1984": { name: "Arboga", county: "Västmanlands län" },
    "2021": { name: "Vansbro", county: "Dalarnas län" },
    "2023": { name: "Malung-Sälen", county: "Dalarnas län" },
    "2026": { name: "Gagnef", county: "Dalarnas län" },
    "2029": { name: "Leksand", county: "Dalarnas län" },
    "2031": { name: "Rättvik", county: "Dalarnas län" },
    "2034": { name: "Orsa", county: "Dalarnas län" },
    "2039": { name: "Älvdalen", county: "Dalarnas län" },
    "2061": { name: "Smedjebacken", county: "Dalarnas län" },
    "2062": { name: "Mora", county: "Dalarnas län" },
    "2080": { name: "Falun", county: "Dalarnas län" },
    "2081": { name: "Borlänge", county: "Dalarnas län" },
    "2082": { name: "Säter", county: "Dalarnas län" },
    "2083": { name: "Hedemora", county: "Dalarnas län" },
    "2084": { name: "Avesta", county: "Dalarnas län" },
    "2085": { name: "Ludvika", county: "Dalarnas län" },
    "2101": { name: "Ockelbo", county: "Gävleborgs län" },
    "2104": { name: "Hofors", county: "Gävleborgs län" },
    "2121": { name: "Ovanåker", county: "Gävleborgs län" },
    "2132": { name: "Nordanstig", county: "Gävleborgs län" },
    "2161": { name: "Ljusdal", county: "Gävleborgs län" },
    "2180": { name: "Gävle", county: "Gävleborgs län" },
    "2181": { name: "Sandviken", county: "Gävleborgs län" },
    "2182": { name: "Söderhamn", county: "Gävleborgs län" },
    "2183": { name: "Bollnäs", county: "Gävleborgs län" },
    "2184": { name: "Hudiksvall", county: "Gävleborgs län" },
    "2260": { name: "Ånge", county: "Västernorrlands län" },
    "2262": { name: "Timrå", county: "Västernorrlands län" },
    "2280": { name: "Härnösand", county: "Västernorrlands län" },
    "2281": { name: "Sundsvall", county: "Västernorrlands län" },
    "2282": { name: "Kramfors", county: "Västernorrlands län" },
    "2283": { name: "Sollefteå", county: "Västernorrlands län" },
    "2284": { name: "Örnsköldsvik", county: "Västernorrlands län" },
    "2303": { name: "Ragunda", county: "Jämtlands län" },
    "2305": { name: "Bräcke", county: "Jämtlands län" },
    "2309": { name: "Krokom", county: "Jämtlands län" },
    "2313": { name: "Strömsund", county: "Jämtlands län" },
    "2321": { name: "Åre", county: "Jämtlands län" },
    "2326": { name: "Berg", county: "Jämtlands län" },
    "2361": { name: "Härjedalen", county: "Jämtlands län" },
    "2380": { name: "Östersund", county: "Jämtlands län" },
    "2401": { name: "Nordmaling", county: "Västerbottens län" },
    "2403": { name: "Bjurholm", county: "Västerbottens län" },
    "2404": { name: "Vindeln", county: "Västerbottens län" },
    "2409": { name: "Robertsfors", county: "Västerbottens län" },
    "2417": { name: "Norsjö", county: "Västerbottens län" },
    "2418": { name: "Malå", county: "Västerbottens län" },
    "2421": { name: "Storuman", county: "Västerbottens län" },
    "2422": { name: "Sorsele", county: "Västerbottens län" },
    "2425": { name: "Dorotea", county: "Västerbottens län" },
    "2460": { name: "Vännäs", county: "Västerbottens län" },
    "2462": { name: "Vilhelmina", county: "Västerbottens län" },
    "2463": { name: "Åsele", county: "Västerbottens län" },
    "2480": { name: "Umeå", county: "Västerbottens län" },
    "2481": { name: "Lycksele", county: "Västerbottens län" },
    "2482": { name: "Skellefteå", county: "Västerbottens län" },
    "2505": { name: "Arvidsjaur", county: "Norrbottens län" },
    "2506": { name: "Arjeplog", county: "Norrbottens län" },
    "2510": { name: "Jokkmokk", county: "Norrbottens län" },
    "2513": { name: "Överkalix", county: "Norrbottens län" },
    "2514": { name: "Kalix", county: "Norrbottens län" },
    "2518": { name: "Övertorneå", county: "Norrbottens län" },
    "2521": { name: "Pajala", county: "Norrbottens län" },
    "2523": { name: "Gällivare", county: "Norrbottens län" },
    "2560": { name: "Älvsbyn", county: "Norrbottens län" },
    "2580": { name: "Luleå", county: "Norrbottens län" },
    "2581": { name: "Piteå", county: "Norrbottens län" },
    "2582": { name: "Boden", county: "Norrbottens län" },
    "2583": { name: "Haparanda", county: "Norrbottens län" },
    "2584": { name: "Kiruna", county: "Norrbottens län" },
}
